CREATE TABLE person(
    id INT,
    name STRING,
    age INT,
    fav ARRAY<STRING>,
    addr MAP<STRING, STRING>
)
COMMENT 'This is the person table'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY '-'
MAP KEYS TERMINATED BY ':'
STORED AS TEXTFILE;